### ISSUE TITLE
Don't throw the "empty heading" error when the element uses ng-bind or ng-bind-html

### ISSUE THREAD

**Issue by ChrisMBarr** [nikestep/html-angular-validate#11]
If i have the following which will output some html into the element

```
<h2 ng-bind-html="user.email | highlight: searchString"></h2>
```

I get the error

> Empty heading.

This feels wrong to me since the header will contain something once angular binds to it.  Could this message be suppressed when the element in question has either the `ng-bind` or `ng-bind-html` attribute on it?

Currently I can set the following to _always_ suppress this error, but it really seems like a workaround/hack

```
relaxerror: [
    'Empty heading.'
],
```

**Comment by pbfrederiksen** [comment]
I agree - I need this change too.

**Comment by nikestep** [comment]
I've always been hesitant to blanket relax errors. This is really a syntactic wrapper, not so much a semantic wrapper. I'm happy to look at a pull request if you've got the time to dig in to how to fix this properly, but I'm not going to be able to get to this.
