### ISSUE TITLE
Fatal error: ENOENT. 'reportpath' folder in path does not exist

### ISSUE THREAD

**Issue by Jacquelin** [nikestep/html-angular-validate#2]
Hello,

I was using grunt-html-angular-validate 0.5.0. Today I update for the new version (0.5.1), this new version now use html-angular-validate npm package (it's why I post this issue here).

My htmlangular task has the option 'reportpath' with a folder in path. Some time this folder does not exist when the task is executed. Until now (in 0.5.0) if the folder does not exist, grunt-html-angular-validate created it. Now, I have this error : 

Running "htmlangular:dist" (htmlangular) task
Fatal error: ENOENT, no such file or directory 'target/html-angular-validate-report.json'

It's not a big deal, for now I downgrade to 0.5.0. I report this case if anyone have the same issue.

I hope created this issue in the right repository. If not just say it and I will create the issue in grunt-html-angular-validate. 

And, thanks for your work :+1:

**Comment by nikestep** [comment]
Yep, an oversight on my part. Thanks for pointing this out!

I've fixed the issue and updated both this and [grunt-html-angular-validate](https://github.com/nikestep/grunt-html-angular-validate) packages on npm.
