### ISSUE TITLE
Getting Fatal error: Cannot read property 'messages' of null

### ISSUE THREAD

**Issue by ftdube** [nikestep/html-angular-validate#20]
Hi,

Overnight, it seems like one of the dependencies from html-angular-validate, w3cjs, got an update from version 0.3.0 to 0.3.1 and a bunch of its own dependencies have changed. From that point on, whenever I try to run htmlangular using grunt-html-angular-validate, I get the following message :
```
Running "htmlangular:main" (htmlangular) task
Fatal error: Cannot read property 'messages' of null

Process finished with exit code 3
```

Does that ring a bell to anyone? Is there an easy way to fix this?

**Comment by jose1984** [comment]
Hi @ftdube,

I had the same problem, I just fixed it with these changes:

[Prevent undefined options](https://github.com/jose1984/html-angular-validate/commit/d6fe3ab5c52afc933a6db7421d2a5b6d9ecfedee)
