### ISSUE TITLE
Support for different report file formats (checkstyle)?

### ISSUE THREAD

**Issue by dpalic** [nikestep/html-angular-validate#5]
We have incorporated yesterday your validator, and we appreciate your great piece of work!

Sadly your validator does not support checkstyle xml format
(e.g. https://code.google.com/p/jslint4java/issues/attachmentText?id=20&aid=7622976105185048938&name=checkstyle-report.xml&token=c4cd7ba934fb48c56f1a8536672c27f1)

Checkstyle is very common in the most analysis toolings which do code metrics analysis and a support would enable also all mixed teams like ours, which work with Java and JavaScript to pull the sources together into one metrics.

Do you see any chance to enhance html-angular-validate with the possibility to support checkstyle reporting? We would be able to support you with this requirement

**Comment by dpalic** [comment]
Nik, it would be great to let us know what you plan with the html-angular-validate on this issue. If unwished to incorporate, fine we will do a workround on our own. If you are open to extend it let us know, we can provide you a contribution to it.

**Comment by nikestep** [comment]
Sorry, pretty busy right now. I'm happy to look into this, but I can't give much of a timeline right now. It'll be a little while. I'm happy to review a pull request if anyone else has time.

**Comment by dpalic** [comment]
Hi Nik,
you said we did ;-)
Would be really great if you could quickly publish the change in a new version. 
Shortly I will also deliver a really minor PR against the grunt task itself (a documentation update)
best wishes
Darko

**Comment by nikestep** [comment]
This has been published under v0.1.5
