### ISSUE TITLE
Add Support for html content

### ISSUE THREAD

**Issue by sumitarora** [nikestep/html-angular-validate#7]
Thanks for the great work

I wanted to have capability to pass raw html to validate also so either override the current method or create the new one.

I implemented the new method naming validateContent will do a PR for review also.

**Comment by nikestep** [comment]
I guess I'm curious what you're trying to do that isn't working. You should be able to validate plain HTML files with this tool as well.

**Comment by sumitarora** [comment]
Yes I am but I want to validate compiled HTML content not the file using it. Basically take my html template compile it with valid data and than validate that compiled html.

**Comment by nikestep** [comment]
I see. While I think that this would be a useful tool, I think it's a separate tool. I'd rather keep this package focused on validating template files.
